//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SILCD.sessoesReunioes.br.gov.camara.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SessoesReunioesSoap", Namespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")]
    public partial class SessoesReunioes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarSituacoesReuniaoSessaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPresencasParlamentarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDiscursosPlenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback obterInteiroTeorDiscursosPlenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPresencasDiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarDiscursosSessoesCongressoEncerradasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SessoesReunioes() {
            this.Url = global::SILCD.Properties.Settings.Default.SILCD_sessoesReunioes_br_gov_camara_www_SessoesReunioes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarSituacoesReuniaoSessaoCompletedEventHandler ListarSituacoesReuniaoSessaoCompleted;
        
        /// <remarks/>
        public event ListarPresencasParlamentarCompletedEventHandler ListarPresencasParlamentarCompleted;
        
        /// <remarks/>
        public event ListarDiscursosPlenarioCompletedEventHandler ListarDiscursosPlenarioCompleted;
        
        /// <remarks/>
        public event obterInteiroTeorDiscursosPlenarioCompletedEventHandler obterInteiroTeorDiscursosPlenarioCompleted;
        
        /// <remarks/>
        public event ListarPresencasDiaCompletedEventHandler ListarPresencasDiaCompleted;
        
        /// <remarks/>
        public event listarDiscursosSessoesCongressoEncerradasCompletedEventHandler listarDiscursosSessoesCongressoEncerradasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarSituacoesReuniaoSessao" +
            "", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarSituacoesReuniaoSessao() {
            object[] results = this.Invoke("ListarSituacoesReuniaoSessao", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarSituacoesReuniaoSessaoAsync() {
            this.ListarSituacoesReuniaoSessaoAsync(null);
        }
        
        /// <remarks/>
        public void ListarSituacoesReuniaoSessaoAsync(object userState) {
            if ((this.ListarSituacoesReuniaoSessaoOperationCompleted == null)) {
                this.ListarSituacoesReuniaoSessaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSituacoesReuniaoSessaoOperationCompleted);
            }
            this.InvokeAsync("ListarSituacoesReuniaoSessao", new object[0], this.ListarSituacoesReuniaoSessaoOperationCompleted, userState);
        }
        
        private void OnListarSituacoesReuniaoSessaoOperationCompleted(object arg) {
            if ((this.ListarSituacoesReuniaoSessaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSituacoesReuniaoSessaoCompleted(this, new ListarSituacoesReuniaoSessaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarPresencasParlamentar", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarPresencasParlamentar(string dataIni, string dataFim, string numMatriculaParlamentar) {
            object[] results = this.Invoke("ListarPresencasParlamentar", new object[] {
                        dataIni,
                        dataFim,
                        numMatriculaParlamentar});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarPresencasParlamentarAsync(string dataIni, string dataFim, string numMatriculaParlamentar) {
            this.ListarPresencasParlamentarAsync(dataIni, dataFim, numMatriculaParlamentar, null);
        }
        
        /// <remarks/>
        public void ListarPresencasParlamentarAsync(string dataIni, string dataFim, string numMatriculaParlamentar, object userState) {
            if ((this.ListarPresencasParlamentarOperationCompleted == null)) {
                this.ListarPresencasParlamentarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPresencasParlamentarOperationCompleted);
            }
            this.InvokeAsync("ListarPresencasParlamentar", new object[] {
                        dataIni,
                        dataFim,
                        numMatriculaParlamentar}, this.ListarPresencasParlamentarOperationCompleted, userState);
        }
        
        private void OnListarPresencasParlamentarOperationCompleted(object arg) {
            if ((this.ListarPresencasParlamentarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPresencasParlamentarCompleted(this, new ListarPresencasParlamentarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarDiscursosPlenario", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarDiscursosPlenario(string dataIni, string dataFim, string codigoSessao, string parteNomeParlamentar, string siglaPartido, string siglaUF) {
            object[] results = this.Invoke("ListarDiscursosPlenario", new object[] {
                        dataIni,
                        dataFim,
                        codigoSessao,
                        parteNomeParlamentar,
                        siglaPartido,
                        siglaUF});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarDiscursosPlenarioAsync(string dataIni, string dataFim, string codigoSessao, string parteNomeParlamentar, string siglaPartido, string siglaUF) {
            this.ListarDiscursosPlenarioAsync(dataIni, dataFim, codigoSessao, parteNomeParlamentar, siglaPartido, siglaUF, null);
        }
        
        /// <remarks/>
        public void ListarDiscursosPlenarioAsync(string dataIni, string dataFim, string codigoSessao, string parteNomeParlamentar, string siglaPartido, string siglaUF, object userState) {
            if ((this.ListarDiscursosPlenarioOperationCompleted == null)) {
                this.ListarDiscursosPlenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDiscursosPlenarioOperationCompleted);
            }
            this.InvokeAsync("ListarDiscursosPlenario", new object[] {
                        dataIni,
                        dataFim,
                        codigoSessao,
                        parteNomeParlamentar,
                        siglaPartido,
                        siglaUF}, this.ListarDiscursosPlenarioOperationCompleted, userState);
        }
        
        private void OnListarDiscursosPlenarioOperationCompleted(object arg) {
            if ((this.ListarDiscursosPlenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDiscursosPlenarioCompleted(this, new ListarDiscursosPlenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/obterInteiroTeorDiscursosPle" +
            "nario", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode obterInteiroTeorDiscursosPlenario(string codSessao, string numOrador, string numQuarto, string numInsercao) {
            object[] results = this.Invoke("obterInteiroTeorDiscursosPlenario", new object[] {
                        codSessao,
                        numOrador,
                        numQuarto,
                        numInsercao});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void obterInteiroTeorDiscursosPlenarioAsync(string codSessao, string numOrador, string numQuarto, string numInsercao) {
            this.obterInteiroTeorDiscursosPlenarioAsync(codSessao, numOrador, numQuarto, numInsercao, null);
        }
        
        /// <remarks/>
        public void obterInteiroTeorDiscursosPlenarioAsync(string codSessao, string numOrador, string numQuarto, string numInsercao, object userState) {
            if ((this.obterInteiroTeorDiscursosPlenarioOperationCompleted == null)) {
                this.obterInteiroTeorDiscursosPlenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterInteiroTeorDiscursosPlenarioOperationCompleted);
            }
            this.InvokeAsync("obterInteiroTeorDiscursosPlenario", new object[] {
                        codSessao,
                        numOrador,
                        numQuarto,
                        numInsercao}, this.obterInteiroTeorDiscursosPlenarioOperationCompleted, userState);
        }
        
        private void OnobterInteiroTeorDiscursosPlenarioOperationCompleted(object arg) {
            if ((this.obterInteiroTeorDiscursosPlenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterInteiroTeorDiscursosPlenarioCompleted(this, new obterInteiroTeorDiscursosPlenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarPresencasDia", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarPresencasDia(string data, string numMatriculaParlamentar, string siglaPartido, string siglaUF) {
            object[] results = this.Invoke("ListarPresencasDia", new object[] {
                        data,
                        numMatriculaParlamentar,
                        siglaPartido,
                        siglaUF});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarPresencasDiaAsync(string data, string numMatriculaParlamentar, string siglaPartido, string siglaUF) {
            this.ListarPresencasDiaAsync(data, numMatriculaParlamentar, siglaPartido, siglaUF, null);
        }
        
        /// <remarks/>
        public void ListarPresencasDiaAsync(string data, string numMatriculaParlamentar, string siglaPartido, string siglaUF, object userState) {
            if ((this.ListarPresencasDiaOperationCompleted == null)) {
                this.ListarPresencasDiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPresencasDiaOperationCompleted);
            }
            this.InvokeAsync("ListarPresencasDia", new object[] {
                        data,
                        numMatriculaParlamentar,
                        siglaPartido,
                        siglaUF}, this.ListarPresencasDiaOperationCompleted, userState);
        }
        
        private void OnListarPresencasDiaOperationCompleted(object arg) {
            if ((this.ListarPresencasDiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPresencasDiaCompleted(this, new ListarPresencasDiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/listarDiscursosSessoesCongre" +
            "ssoEncerradas", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode listarDiscursosSessoesCongressoEncerradas(string dataini, string datafim) {
            object[] results = this.Invoke("listarDiscursosSessoesCongressoEncerradas", new object[] {
                        dataini,
                        datafim});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void listarDiscursosSessoesCongressoEncerradasAsync(string dataini, string datafim) {
            this.listarDiscursosSessoesCongressoEncerradasAsync(dataini, datafim, null);
        }
        
        /// <remarks/>
        public void listarDiscursosSessoesCongressoEncerradasAsync(string dataini, string datafim, object userState) {
            if ((this.listarDiscursosSessoesCongressoEncerradasOperationCompleted == null)) {
                this.listarDiscursosSessoesCongressoEncerradasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarDiscursosSessoesCongressoEncerradasOperationCompleted);
            }
            this.InvokeAsync("listarDiscursosSessoesCongressoEncerradas", new object[] {
                        dataini,
                        datafim}, this.listarDiscursosSessoesCongressoEncerradasOperationCompleted, userState);
        }
        
        private void OnlistarDiscursosSessoesCongressoEncerradasOperationCompleted(object arg) {
            if ((this.listarDiscursosSessoesCongressoEncerradasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarDiscursosSessoesCongressoEncerradasCompleted(this, new listarDiscursosSessoesCongressoEncerradasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListarSituacoesReuniaoSessaoCompletedEventHandler(object sender, ListarSituacoesReuniaoSessaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSituacoesReuniaoSessaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSituacoesReuniaoSessaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListarPresencasParlamentarCompletedEventHandler(object sender, ListarPresencasParlamentarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPresencasParlamentarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPresencasParlamentarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListarDiscursosPlenarioCompletedEventHandler(object sender, ListarDiscursosPlenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDiscursosPlenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDiscursosPlenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void obterInteiroTeorDiscursosPlenarioCompletedEventHandler(object sender, obterInteiroTeorDiscursosPlenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterInteiroTeorDiscursosPlenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterInteiroTeorDiscursosPlenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListarPresencasDiaCompletedEventHandler(object sender, ListarPresencasDiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPresencasDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPresencasDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void listarDiscursosSessoesCongressoEncerradasCompletedEventHandler(object sender, listarDiscursosSessoesCongressoEncerradasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarDiscursosSessoesCongressoEncerradasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarDiscursosSessoesCongressoEncerradasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591